apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: jcbeasg1w-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-519f8d656f.jaj7.p3.openshiftapps.com/rhtap/rhtap-qe-java-springboot:0b4c211fda336162556896b403c890f3984f8ab6@sha256:adbad8ac610ec9edc76d5bae99131775e7f29446860d692d90e9037b03189b4c
          name: container-image
